services:
  app:
    build: .
    init: true
    user: "0:0"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    command: python run.py
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: 4G